### ISSUE TITLE
<base href="/"> is needed in index.html's <head>

### ISSUE THREAD

**Issue by olive009** [platosha/angular2-polymer-quickstart#2]
otherwise there would be some errors in chrome
`EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.`

**Comment by platosha** [comment]
Strange, there is `<base href="/">` in the head already, see:

https://github.com/vaadin/angular2-polymer-quickstart/blob/5cbe3f1c66785b4701a244c343681f4a739592a5/index.html#L4

**Comment by platosha** [comment]
I can not reproduce this. As already said, the tag is there in the `index.html` file.

This might occur if you use the `vulcanize` tool with the index.html file. Vulcanize removes the tag. In this case, I would suggest to remove the `<base href="/">` tag before running `$ vulcanize`, and then add back after.

Closing for now. Feel free to comment if you have anything to add.
