### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by woifal** [platosha/angular2-polymer-quickstart#7]
"npm i && bower i" give me the following error:

npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'angular/core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'angular2-polymer-quickstart'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "d:\\private\\nodejs\\node.exe" "d:\\private\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! cwd d:\Demands\angular_polymer\vaadin
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code E404

any advice on how to fix this?

**Comment by samiheikki** [comment]
Hi @woifal 

For me it is working fine and angular/core is found in the npm registry. https://www.npmjs.com/package/%2540angular%2Fcore

Try to update your npm and run it again.
