### ISSUE TITLE
Example with Angular-CLI

### ISSUE THREAD

**Issue by hegsie** [platosha/angular2-polymer-quickstart#8]
Hey Guys, 
I'm sure I'm doing something wrong but when I try and port this example over to the angular-CLI project format I can't seem to get it working, has anyone tried to get it operational in a CLI project?
Regards

**Comment by samiheikki** [comment]
Angular-CLI (Webpack) version requires some additional configuration. Follow the steps in our documentation: https://vaadin.com/docs/-/part/elements/angular2-polymer/ng-cli-webpack.html and should work that way. Please notice that currently angular2-polymer does not work with v.2.2.0 of Angular. As a workaround you can use Angular 2.1.x version.

**Comment by hegsie** [comment]
So i figured out where my code was different, it looks like using the 
`<script src="assets/bower_components/webcomponentsjs/webcomponents-lite.min.js">`
fixed my isssue where in my code I seems to have picked up using 
`<script src="assets/bower_components/webcomponentsjs/webcomponents.js">`
somewhere, looks like using the polyfill shdaow DOM from webcomponents.js, in the example breaks the button call to drawer.toggle()

Thanks for the pointer to your page :)
